---
title: "Tarea 03"
author: "Josshua Cordero Barboza (B92289)"
date: "28/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cargar bibliotecas

```{r carga librerias, message=FALSE, warning=FALSE}
library(sf)
library(dplyr)
library(leaflet)
library(plotly)
library(DT)
```

## Cargar documentos 
```{r carga doc, message=FALSE, warning=FALSE}
# Carga de primates 
prim <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/primates-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
st_crs(prim) = 4326
# Carga de cantones
cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
)
```

## Comando para cruzar datos
```{r datos cruzados}
prim<- 
 prim %>%
 st_join(cantones["canton"])
```

# Parte 1

## Tabla de primates avistados en Costa Rica
```{r tabla primates}
prim %>%
  st_drop_geometry() %>%
  select(family,
         species,
         stateProvince,
         canton,
         eventDate
         ) %>%
  DT::datatable(
    colnames = c("Familia", "Especie", "Provincia", "Cant칩n", "Fecha"),
    rownames = FALSE,
    options = list(
      searchHighlight = TRUE,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

# Parte 2

## Gr치fico de pastel
```{r primates pastel, message=FALSE, warning=FALSE}
Primtot <- data.frame("species"=rownames(prim), prim)
dataprim <- prim[,c('species', 'year')]

figprim <- plot_ly(dataprim, labels = ~species, values = ~year, type = 'pie')
figprim <- figprim %>% layout(title = 'Avistamiento de primates por especie en Costa Rica (1839-2021).',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

figprim
```

# Parte 3
## Mapa Leaflet

```{r filtrado especies}
alouatta_palliata <-
  prim %>%
  filter(species == "Alouatta palliata")
cebus_capucinus <-
  prim %>%
  filter(species == "Cebus capucinus")
ateles_geoffroyi <-
  prim %>%
  filter(species == "Ateles geoffroyi")
saimiri_oerstedii <-
  prim %>%
  filter(species == "Saimiri oerstedii")
```



```{r mapa, message=FALSE, warning=FALSE}

alouatta_palliata %>%
  select(stateProvince,
         canton,
         locality,
         eventDate) %>%
  leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Im치genes de ESRI") %>%
  addCircleMarkers(
    stroke = F,
    radius = 4,
    fillColor = 'red',
    fillOpacity = 1,
    popup = paste(
      alouatta_palliata$stateProvince,
      alouatta_palliata$canton,
      alouatta_palliata$locality,
      alouatta_palliata$eventDate,
      sep = '<br/>'
    ),
    group = "alouatta"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Im치genes de ESRI"),
    overlayGroups = c("alouatta")
  ) %>%
  addMiniMap(
    tiles = providers$Stamen.OpenStreetMap.Mapnik,
    position = "bottomleft",
    toggleDisplay = TRUE
  )
```

